# file: logwatch/tasks/main.yml

- name: ensure software is installed
  apt:
    pkg: "{{item}}"
    state: present
  when: ansible_os_family == 'Debian'
  with_items:
    - libdate-manip-perl
    - logwatch
  tags:
    - logwatch
    - packages

- name: ensure software is installed
  yum:
    pkg: "{{item}}"
    state: present
  when: ansible_os_family == 'RedHat'
  with_items:
    - logwatch
  tags:
    - logwatch
    - packages

- name: ensure logwatch configure (/etc/logwatch/conf/logwatch.conf) is correct
  template:
    src: etc_logwatch_conf_logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - logwatch
    - configuration

- name: ensure there is no daily logwatch cron file
  file:
    path: "/etc/cron.daily/{{ logwatch_cron_file_name }}"
    state: absent
  when: logwatch_cron_time != 'daily'
  tags:
    - logwatch
    - cron
    - configuration

- name: ensure logwatch cron files exist in appropriate directory
  template:
    src: logwatch.j2
    dest: "/etc/cron.{{ logwatch_cron_time }}/{{ logwatch_cron_file_name }}"
    owner: root
    group: root
    mode: 0755
  when: logwatch_cron_time != 'daily'
  tags:
    - logwatch
    - cron
    - configuration

- name: touch /var/cache/logwatch to stop logwatch failing (ubuntu 12.04)
  file:
    dest=/var/cache/logwatch
    state=directory
  tags:
    - logwatch
