# file: logwatch/tasks/main.yml

- name: Logwatch | Make sure logwatch and its dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - libdate-manip-perl
    - logwatch
  tags:
    - logwatch
    - packages

- name: Logwatch | Configure logwatch (/etc/logwatch/conf/logwatch.conf)
  template:
    src: etc_logwatch_conf_logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
    owner: root
    group: root
    mode: 0644
  - tags:
    - logwatch
    - configuration

- name: move logwatch cron from daily to weekly
  shell: if [ -f /etc/cron.daily/00logwatch ]; then mv /etc/cron.daily/00logwatch /etc/cron.weekly/; echo "moved 00logwatch"; fi
  register: move_result
  changed_when: "move_result.stdout == 'moved 00logwatch'"
  tags:
    - logwatch
    - configuration

- name: touch /var/cache/logwatch to stop logwatch failing (ubuntu 12.04)
  file:
    dest=/var/cache/logwatch
    state=directory
  tags:
    - logwatch
