# file: logwatch/tasks/main.yml

- name: Logwatch | Make sure logwatch and its dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - libdate-manip-perl
    - logwatch
  tags:
    - logwatch
    - packages

- name: Logwatch | Configure logwatch (/etc/logwatch/conf/logwatch.conf)
  template:
    src: etc_logwatch_conf_logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
    owner: root
    group: root
    mode: 0644
  - tags:
    - logwatch
    - configuration

- name: Logwatch | Remove logwatch's cronjob
  file:
    path: /etc/cron.daily/00logwatch
    state: absent

- name: add modified logwatch to "{{ logwatch_cron_time }}" cron
  template:
    src: 00logwatch.j2
    dest: "/etc/cron.{{ logwatch_cron_time }}/00logwatch"
    owner: root
    group: root
    mode: 0755
  tags:
    - logwatch
    - cron
    - configuration

- name: touch /var/cache/logwatch to stop logwatch failing (ubuntu 12.04)
  file:
    dest=/var/cache/logwatch
    state=directory
  tags:
    - logwatch
